from os import getenv

CLOUD_NAME = getenv("CLOUD_NAME")
CLOUD_API_KEY = getenv("CLOUD_API_KEY")
CLOUD_API_SECRET = getenv("CLOUD_API_SECRET")

SECRET_KEY = getenv("SECRET_KEY")
MYSQL_HOST = getenv("MYSQL_HOST")
MYSQL_USER = getenv("MYSQL_USER")
MYSQL_PASSWORD = getenv("MYSQL_PASSWORD")
MYSQL_DB = getenv("MYSQL_DB")
MYSQL_PORT = int(getenv("MYSQL_PORT", 3306))
MYSQL_UNIX_SOCKET = getenv("MYSQL_UNIX_SOCKET") or None
MYSQL_CONNECT_TIMEOUT = int(getenv("MYSQL_CONNECT_TIMEOUT", 10))
MYSQL_READ_DEFAULT_FILE = getenv("MYSQL_READ_DEFAULT_FILE") or None
MYSQL_USE_UNICODE = getenv("MYSQL_USE_UNICODE", "True").lower() in ("true", "1", "yes")
MYSQL_CHARSET = getenv("MYSQL_CHARSET", "utf8")
MYSQL_SQL_MODE = getenv("MYSQL_SQL_MODE") or None
MYSQL_CURSORCLASS = getenv("MYSQL_CURSORCLASS") or None
MYSQL_AUTOCOMMIT = getenv("MYSQL_AUTOCOMMIT", "True").lower() in ("true", "1", "yes")
MYSQL_CUSTOM_OPTIONS = {}
